@extends('layouts.report-main-header')

@section('content')
    <section id="wrapper">

        @include('layouts.sidebar')

        <div id="page-content-wrapper" class="p-b-100">

			<div class="row py-3 d1-bg ps-5 align-items-center">
                <div class="col-lg-2">
                    <h3 class="headingH3">Due Report</h3>
                </div>
				<div class="col-lg-4">
                    <div class="search-container">
						<input type="text" id="search" class="form-search" placeholder="Type to Search"/>
						<i class="fa-solid fa-magnifying-glass f-20"></i>
                	</div>
				</div>
				<div class="col-lg-6 d-flex justify-content-end pe-5">
					@include('layouts.profile')
                </div>
			</div>

 <!-- Page content -->

            <div class="px-4 pt-4">

            <a href="{{ route('reports.repayments') }}"><button class="main-button d5-bg d1 mb-3">Repayment Report</button></a>

			<table id="searchtbl" class="table" style="width:100%">
				<thead class="table-header">

					<tr>
                        <th>Patient</th>
                        <th>Phone</th>
						<th class="text-end">Total Due</th>
                        <!-- <th class="text-end">Last Repayment</th> -->
					</tr>

				</thead>
				<tbody>
				@if(isset($dues))
				@foreach ($dues as $due)

					<tr>
						<td>{{ $due->patient->name }}<br /> {{ $due->patient->reg_no }}</td>
                        <td>{{ $due->patient->contact_number }}</td>
						<td class="text-end">{{ number_format($due->total_due_amount, 2) }}</td>
						<!-- <td class="text-end">@if($due->repayments->last())
                                {{ number_format($due->repayments->last()->paid_amount, 2) }}
                            @else
                                0.00
                            @endif
                        </td> -->
					</tr>
				@endforeach
				@endif

			</table>

            <h5 id="totalDues" class="headingH6 mt-4">Total Due :  {{ number_format($total_dues??0, 2) }}</h5>

        </div>

            <!-- Page content end -->
        </div>
    </section>

@endsection

@push('js')
<script>
    $(document).ready(function() {
            var table = $('#searchtbl').DataTable({
                "language": {
                "paginate": {
                "previous": "<",
                "next": ">"
                }
            },
            "bLengthChange" : true,
            columnDefs: [
                { orderable: false }
            ],
            layout: {
                    topEnd: {
                        buttons: ['excel'],
                    }
                },
            });

            table.button().add(0, {
                extend: 'pdfHtml5',
                title: function () {
                    return 'Due Report';
                },
                customize: function(doc) {
                    doc.content.splice(0, 1, {
                        text: 'Due Report',
                        fontSize: 18,
                        alignment: 'center',
                        margin: [0, 0, 0, 8]
                    });

                    doc.content[1].table.widths = Array(table.columns().count()).fill('*');
                    var rowCount = doc.content[1].table.body.length;
                    var columnCount = doc.content[1].table.body[0].length; // Assuming all rows have the same length

                    for (var i = 0; i < rowCount; i++) {
                        for (var j = 0; j < columnCount; j++) {
                            doc.content[1].table.body[i][0].alignment = 'left';
                            doc.content[1].table.body[i][1].alignment = 'left';
                            doc.content[1].table.body[i][2].alignment = 'right';
                        }
                    }

                    doc.content.push({
                        text: 'Generated by PMC',
                        margin: [0, 20, 0, 0],
                        alignment: 'center',
                        fontSize: 10
                    });
                }
            });

             // Recalculate total sales on DataTable redraw
             table.on('draw', function () {
                var totalDues = 0;
                table.rows({search: 'applied'}).data().each(function (value, index) {
                    totalDues += parseFloat(value[2].replace(/[^0-9.-]+/g,""));
                });
                $('#totalDues').text('Total Due : ' + totalDues.toFixed(2));
            });

            $('#search').keyup(function() {
                var table = $('#searchtbl').DataTable();
                table.search($(this).val()).draw();
            });
        });
</script>
@endpush

