@extends('layouts.report-main-header')

@section('content')
    <section id="wrapper">

        @include('layouts.sidebar')

        <div id="page-content-wrapper" class="p-b-100">

			<div class="row py-3 d1-bg ps-5 align-items-center">
                <div class="col-lg-2">
                    <h3 class="headingH3">Repayment Report</h3>
                </div>
				<div class="col-lg-4">
                    <div class="search-container">
						<input type="text" id="search" class="form-search" placeholder="Type to Search"/>
						<i class="fa-solid fa-magnifying-glass f-20"></i>
                	</div>
				</div>
				<div class="col-lg-6 d-flex justify-content-end pe-5">
					@include('layouts.profile')
                </div>
			</div>

 <!-- Page content -->

            <div class="px-4 pt-4">

			<table id="searchtbl" class="table" style="width:100%">
				<thead class="table-header">

					<tr>
                        <th>Date</th>
                        <th>Patient Name</th>
                        <th>Phone</th>
						<th class="text-end">Amount</th>
					</tr>

				</thead>
				<tbody>
				@if(isset($repayments))
				@foreach ($repayments as $repayment)
					<tr>
                        <td>{{ $repayment->created_at }}</td>
						<td>{{ $repayment->patient->name }}<br /> {{ $repayment->patient->reg_no }}</td>
                        <td>{{ $repayment->patient->contact_number }}</td>
						<td class="text-end">{{ number_format($repayment->paid_amount, 2) }}</td>
					</tr>
				@endforeach
				@endif

			</table>

            @php
                $totalRepayment = $repayments->sum('paid_amount');
            @endphp

            <h5 class="headingH6 mt-4">Total Repayment :&nbsp;&nbsp; {{ number_format($totalRepayment??0, 2) }}</h5>

        </div>

            <!-- Page content end -->
        </div>
    </section>

@endsection

@push('js')
<script>
    $(document).ready(function() {
            var table = $('#searchtbl').DataTable({
                "language": {
                "paginate": {
                "previous": "<",
                "next": ">"
                }
            },
            "bLengthChange" : true,
            columnDefs: [
                { orderable: false }
            ],
            layout: {
                    topEnd: {
                        buttons: ['excel'],
                    }
                },
            });

            table.button().add(0, {
                extend: 'pdfHtml5',
                title: function () {
                    return 'Repayment Report';
                },
                customize: function(doc) {
                    doc.content.splice(0, 1, {
                        text: 'Repayment Report',
                        fontSize: 18,
                        alignment: 'center',
                        margin: [0, 0, 0, 8]
                    });
                    doc.content[1].table.widths = Array(table.columns().count()).fill('*');
                    var rowCount = doc.content[1].table.body.length;
                    var columnCount = doc.content[1].table.body[0].length; // Assuming all rows have the same length

                    for (var i = 0; i < rowCount; i++) {
                        for (var j = 0; j < columnCount; j++) {
                            doc.content[1].table.body[i][0].alignment = 'left';
                            doc.content[1].table.body[i][1].alignment = 'left';
                            doc.content[1].table.body[i][2].alignment = 'right';
                        }
                    }

                    doc.content.push({
                        text: 'Generated by PMC',
                        margin: [0, 20, 0, 0],
                        alignment: 'center',
                        fontSize: 10
                    });
                }
            });

            $('#search').keyup(function() {
                var table = $('#searchtbl').DataTable();
                table.search($(this).val()).draw();
            });
        });
</script>
@endpush

